version: '3'
services:
  mongodb:
    image: mongo:6.0.4-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    environment:
      - UID=${UID}
      - GID=${GID}
    user: '${UID}:${GID}'
    networks:
      - messages-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - messages-network

networks:
  messages-network:
    driver: bridge